{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}

module Options
  ( Options(..)
  , optionsParser
  , getOptions
  , GenType(..)
  , genTypeToText
  , ModuleName
  , Header
  ) where

import           Data.Text           (Text)
import qualified Data.Text           as T
import           Data.Version        (showVersion)
import           Options.Applicative
import           Paths_xsd_isogen    (version)
import           Data.List


data GenType = Parser | Generator | Both
  deriving (Read, Show, Eq, Bounded, Enum)

genTypeToText :: GenType -> Text
genTypeToText Parser    = "Parser"
genTypeToText Generator = "Generator"
genTypeToText Both      = "Both"

type ModuleName = Text
type Header = Text

data Options = Options
  { oHeader :: Maybe Header
  , oMode :: GenType
  , oInput :: FilePath
  , oModule :: ModuleName
  }
  deriving (Show)

optionsParser :: Parser Options
optionsParser = Options
  <$> ( flag' Nothing
    ( long "no-header"
    <> help "Do not place a header at the top of the file."
    ) <|> Just <$> strOption
    ( long "header"
    <> help "A custom header to be placed at the top of the file."
    <> value ("This file was generated by xsd-isogen version "
      <> T.pack (showVersion version)
      <> "\nhttps://github.com/dredozubov/xsd-isogen")
    )
  )
  <*> option auto
    ( long "mode"
    <> short 'm'
    <> value Both
    <> help ("Whether to generate both parsers and generators. One of: "
      <> (mconcat . intersperse ", " . fmap show
        $ [minBound @GenType .. maxBound]) <> ".")
    )
  <*> strOption
    ( long "input"
    <> short 'i'
    <> help "Path to the input .xsd file."
    )
  <*> strOption
    ( long "name"
    <> short 'n'
    <> help "Specify the name of the generated module."
    <> value "Dummy"
    )


getOptions :: IO Options
getOptions = execParser $ info (optionsParser <**> helper)
  $ fullDesc
  <> header
    ( "xsd-isogen version " <> showVersion version
    <> " (https://github.com/dredozubov/xsd-isogen)"
    )
  <> progDesc ( "A tool for generating xml-isogen-compatible "
    <> "(https://github.com/typeable/xml-isogen) .hs files from .xsd files."
    )
