-- This file was generated by xsd-isogen version 0.1.0.0
-- https://github.com/dredozubov/xsd-isogen

{-# OPTIONS_GHC -Wno-unused-imports #-}
module Dummy where

import Control.DeepSeq
import Data.Scientific
import Data.THGen.XML
import Text.XML.DOM.Parser
import Text.XML.Writer
import Text.XML.ParentAttributes
import Prelude hiding ((*), (+))


{-|
Generated from: X
-}
"X" =:= record ParserAndGenerator
  ! "s" [t|Text|]

{-|
Generated from: A
-}
"A" =:= record ParserAndGenerator
  ! "s" [t|Text|]
  ! "x" [t|XmlX|]
  ! "i" [t|Integer|]

{-|
Generated from: B
-}
"B" =:= record ParserAndGenerator
  ! "s" [t|Text|]

{-|
Generated from: C
-}
"C" =:= record ParserAndGenerator
  ! "s" [t|Text|]
  ! "x" [t|XmlX|]

data AnyXmlC
  = TheXmlC !XmlC
  | TheXmlA !XmlA
  deriving (Eq, Show)

instance NFData AnyXmlC where
  rnf = rwhnf
 
instance FromDom AnyXmlC where
  fromDom = do
    tp <- parseAttribute
      (matchName "{http://www.w3.org/2001/XMLSchema-instance}type")
      Right
    case tp of
      "C" -> TheXmlC <$> fromDom
      "A" -> TheXmlA <$> fromDom
      _ -> throwParserError (PEOther "Unexpected type")

instance ToXML AnyXmlC where
  toXML (TheXmlC a) = toXML a
  toXML (TheXmlA a) = toXML a

instance ToXmlParentAttributes AnyXmlC where
  toXmlParentAttributes (TheXmlC a) =
    ("{http://www.w3.org/2001/XMLSchema-instance}type", "C")
    : toXmlParentAttributes a
  toXmlParentAttributes (TheXmlA a) =
    ("{http://www.w3.org/2001/XMLSchema-instance}type", "A")
    : toXmlParentAttributes a
data AnyXmlB
  = TheXmlB !XmlB
  | TheAnyXmlC !AnyXmlC
  deriving (Eq, Show)

instance NFData AnyXmlB where
  rnf = rwhnf
 
instance FromDom AnyXmlB where
  fromDom = do
    tp <- parseAttribute
      (matchName "{http://www.w3.org/2001/XMLSchema-instance}type")
      Right
    case tp of
      "B" -> TheXmlB <$> fromDom
      "C" -> TheAnyXmlC <$> fromDom
      _ -> throwParserError (PEOther "Unexpected type")

instance ToXML AnyXmlB where
  toXML (TheXmlB a) = toXML a
  toXML (TheAnyXmlC a) = toXML a

instance ToXmlParentAttributes AnyXmlB where
  toXmlParentAttributes (TheXmlB a) =
    ("{http://www.w3.org/2001/XMLSchema-instance}type", "B")
    : toXmlParentAttributes a
  toXmlParentAttributes (TheAnyXmlC a) =
    ("{http://www.w3.org/2001/XMLSchema-instance}type", "C")
    : toXmlParentAttributes a

