-- This file was generated by xsd-isogen version 0.1.0.0
-- https://github.com/dredozubov/xsd-isogen

{-# OPTIONS_GHC -Wno-unused-imports #-}
module Dummy where

import Control.DeepSeq
import Data.Scientific
import Data.THGen.XML
import Text.XML.DOM.Parser
import Text.XML.Writer
import Text.XML.ParentAttributes
import Prelude hiding ((*), (+))


{-|
Generated from: str
-}
newtype XmlStr
  = XmlStr
  { unXmlStr :: Text
  } deriving (Show, Eq, NFData, ToXML)

instance FromDom XmlStr where
  fromDom = XmlStr <$> fromDom

{-|
Generated from: customer
-}
"Customer" =:= record Both
  ! "firstName" [t|XmlStr|]
  ! "lastName" [t|XmlStr|]


