-- This file was generated by xsd-isogen version 0.1.0.0
-- https://github.com/dredozubov/xsd-isogen

{-# OPTIONS_GHC -Wno-unused-imports #-}
module Dummy where

import Control.DeepSeq
import Data.Scientific
import Data.THGen.XML
import Text.XML.DOM.Parser
import Text.XML.Writer
import Text.XML.ParentAttributes
import Prelude hiding ((*), (+))


{-|
Generated from: stringtype

Blah
-}

newtype XmlStringtype
  = XmlStringtype
  { unXmlStringtype :: Text
  } deriving (Show, Eq, NFData, ToXML)

instance FromDom XmlStringtype where
  fromDom = XmlStringtype <$> fromDom

{-|
Generated from: a
-}

"A" =:= record Both
  ! "a" [t|XmlStringtype|]
  ! "b" [t|XmlStringtype|]
  ? "c" [t|XmlStringtype|]
  + "d" [t|XmlStringtype|]
  + "e" [t|XmlStringtype|]
  ! "f" [t|Scientific|]


